#version 330 core

// Depth-only pass — no color writes. The empty main() is enough; the depth
// value is generated by gl_Position and written by the fixed-function depth
// stage automatically.
void main() {}
